#!/bin/bash

# Add nodejs repo.
sudo mkdir -p /etc/apt/keyrings
sudo rm -v /etc/apt/keyrings/nodesource.gpg
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_current.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

# Attempt to install dependencies using APT.
sudo apt install --assume-yes build-essential cmake python3-dev mono-complete golang nodejs openjdk-17-jdk openjdk-17-jre npm #vim-nox

# Compile ycm.
origin="$(pwd)"
cd ~/.vim/bundle/YouCompleteMe
python3 install.py --all
cd "${origin}"
