#!/bin/bash

# Attempt to install vim with scripting language support using APT.
sudo apt install --assume-yes python3-dev vim-nox

# Create directory if it doesn't exist.
mkdir -p ~/.vim/autoload

# Install vim-plug.
wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy the vimrc to home directory.
cp -v vimrc ~/.vimrc

# Copy the plugin list file to home directory.
cp -v vim-plug-plugins ~/.vim/vim-plug-plugins

echo "To finish installing kaku, execute :PlugInstall next time you run vim."
