#!/bin/bash

# Attempt to install vim with scripting language support using APT.
sudo apt install --assume-yes vim-gtk3

# Remove old vim directory.
sudo rm -rv ~/.vim

# Install vim-plug.
mkdir -p ~/.vim/autoload
wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Copy the vimrc to home directory.
cp -v vimrc ~/.vimrc

# Copy the plugin list file to home directory.
cp -v plugs ~/.vim/plugs

# Install plugins.
vim +PlugInstall +qa

echo "kaku installed."
