#!/bin/bash

# Attempt to install vim with scripting language support using APT.
sudo apt install --assume-yes python3-dev vim-gtk3

# Remove old Vundle.
sudo rm -rv ~/.vim/bundle/Vundle.vim

# Install Vundle.
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Copy the vimrc to home directory.
cp -v vimrc ~/.vimrc

# Copy the plugin list file to home directory.
cp -v vundles ~/.vim/vundles

# Install plugins.
vim +PluginInstall +qall

# Install YouCompleteMe.
#source install-ycm

echo "kaku installed."
